name: Continuous Integration
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.7
      - name: Cache virtualenv
        if: runner.os == 'macOS'
        id: cache-virtualenv-macos
        uses: actions/cache@v2
        with:
          path: ~/Library/Caches/pypoetry/virtualenvs
          key: ${{ runner.os }}-virtualenvs
      - name: Cache virtualenv
        if: runner.os == 'Windows'
        id: cache-virtualenv-windows
        uses: actions/cache@v2
        with:
          path: C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs
          key: ${{ runner.os }}-virtualenvs
      - name: Install dependencies
        run: poetry install
      - name: Run linting
        if: runner.os == 'macOS'
        run: find . -type f -name "*.py" | xargs poetry run pylint 
      - name: Run tests
        run: poetry run pytest -n 4